var dir_7440c80a84150c89eded6c163cdc56e5 =
[
    [ "access.cpp", "access_8cpp_source.html", null ],
    [ "accessors.cpp", "accessors_8cpp_source.html", null ],
    [ "algorithms.cpp", "algorithms_8cpp_source.html", null ],
    [ "arithmetic_elementwise.cpp", "arithmetic__elementwise_8cpp_source.html", null ],
    [ "arithmetic_hadamard.cpp", "arithmetic__hadamard_8cpp_source.html", null ],
    [ "arithmetic_scalar.cpp", "arithmetic__scalar_8cpp_source.html", null ],
    [ "arithmetic_unary.cpp", "arithmetic__unary_8cpp_source.html", null ],
    [ "assignment_returns_self.cpp", "assignment__returns__self_8cpp_source.html", null ],
    [ "comparison.cpp", "comparison_8cpp_source.html", null ],
    [ "concepts.cpp", "concepts_8cpp_source.html", null ],
    [ "construct.cpp", "construct_8cpp_source.html", null ],
    [ "construct_from_buffer.cpp", "construct__from__buffer_8cpp_source.html", null ],
    [ "dot.cpp", "dot_8cpp_source.html", null ],
    [ "factories.cpp", "factories_8cpp_source.html", null ],
    [ "fill.cpp", "fill_8cpp_source.html", null ],
    [ "formatter.cpp", "formatter_8cpp_source.html", null ],
    [ "hash.cpp", "hash_8cpp_source.html", null ],
    [ "instantiation.cpp", "instantiation_8cpp_source.html", null ],
    [ "iterators.cpp", "iterators_8cpp_source.html", null ],
    [ "main.cpp", "test_2src_2main_8cpp_source.html", null ],
    [ "matmul.cpp", "matmul_8cpp_source.html", null ],
    [ "matrix_from_view.cpp", "matrix__from__view_8cpp_source.html", null ],
    [ "matrix_view.cpp", "matrix__view_8cpp_source.html", null ],
    [ "matrix_view_io.cpp", "matrix__view__io_8cpp_source.html", null ],
    [ "nested_init.cpp", "nested__init_8cpp_source.html", null ],
    [ "ostream.cpp", "ostream_8cpp_source.html", null ],
    [ "reductions.cpp", "reductions_8cpp_source.html", null ],
    [ "reshape.cpp", "reshape_8cpp_source.html", null ],
    [ "rows_cols.cpp", "rows__cols_8cpp_source.html", null ],
    [ "size_data.cpp", "size__data_8cpp_source.html", null ],
    [ "slice.cpp", "slice_8cpp_source.html", null ],
    [ "transpose.cpp", "transpose_8cpp_source.html", null ],
    [ "typedefs.cpp", "typedefs_8cpp_source.html", null ]
];